version: '3.9'

x-common-variables:
  &common-variables
  ASPNETCORE_ENVIRONMENT: development
  HOST_HOSTNAME: ${HOSTNAME}

services:
  reactapp:
    container_name: reactapp_container
    image: ${DOCKER_REGISTRY-}_reactapp:${REACTAPP_VERSION:-latest}
    build:
      dockerfile: ${REACTAPP_DOCKERFILE}
      context: ./reactapp
    # depends_on:
    #   - rabbitmq0
    environment:
      <<: *common-variables
      NODE_ENV: development
      # FAST_REFRESH: "false"
      # CHOKIDAR_USEPOLLING: "true"
      # WDS_SOCKET_PORT: 0
    volumes:
      - './reactapp:/app'
      - 'reactapp_node_modules:/app/node_modules'
    ports:
      - ${REACTAPP_PUBLIC_PORT}:${REACTAPP_PORT}
    stdin_open: true
    tty: true
    networks:
      - env_net
    restart: unless-stopped
networks:
  env_net:
    external: true

volumes:
  reactapp_node_modules:
