version: '3.9'

x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: development
  HOST_HOSTNAME: ${HOSTNAME}

services:
  webapp:
    container_name: react_app
    image: ${DOCKER_REGISTRY-}webapp:1.0
    build: 
      dockerfile: ${WEBAPP_DOCKERFILE}
      context: ./webapp
    # depends_on:
    #   - rabbitmq0
    environment:
      <<: *common-variables
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './webapp:/app'
      - 'webapp_node_modules:/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - env_net
    restart: unless-stopped
networks:
  env_net:
    external: true

volumes:
  webapp_node_modules: