apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  selector:
    matchLabels:
      app: reactapp-deployment
      tier: reactapp-pod
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: reactapp-deployment
        tier: reactapp-pod
        track: stable
    spec:
      containers:
      - name: reactapp-container
        image: reactapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        # env:
        #   - name: ASPNETCORE_URLS
        #     value: http://+:80
        #   - name: REACT_APP_SERVER_URL
        #     value: http://coreapi-pod