apiVersion: v1
kind: Service
metadata:
  name: reactapp-pod
spec:
  selector:
    app: dln
    tier: reactapp-pod
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 32000
  type: LoadBalancer