# Use an official Tomcat runtime as a parent image
FROM tomcat:9-jre11

# Remove the default ROOT webapp
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file into the container
COPY build/libs/*.war /usr/local/tomcat/webapps/ROOT.war

# Expose the default Tomcat port
EXPOSE 8080

# Start Tomcat when the container starts
CMD ["catalina.sh", "run"]